### ISSUE TITLE
Where are conventional commits ?

### ISSUE THREAD

**Issue by Nowp** [Banalian/ProjectNeighbourGraph#1]

**Comment by Banalian** [comment]
i suggest you check commit 8a14d86 , does it looks correct to you ?

**Comment by Banalian** [comment]
i'm gonna assume it is and close this issue

**Comment by Nowp** [comment]
NOPE, it is feat(optional-scope): Your clear message

**Comment by Banalian** [comment]
i'll do better next time then !
